#docker-compose.ymlのバージョン
version: '3.8'
#docker volumeの設定
volumes:
  docker-volume:

services:
  # Webサーバー
  web:
    image: nginx:1.18
    ports:
      - '8000:80'
    depends_on:
      - app
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
  # アプリケーションサーバー
  app:
    build: ./docker/php
    volumes:
      - .:/var/www/html
  # データベース
  db:
    build: ./docker/mysql
    ports:
      - 3305:3306
    volumes:
      - docker-volume:/var/lib/mysql
